jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: github_app_token
      name: GitHub App token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.APP_ID }}
        installation_id: 22958780
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - continue-on-error: true
      id: tag
      name: Get tag
      uses: dawidd6/action-get-tag@v1
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        bodyFile: release-notes/opensearch.release-notes-${{steps.tag.outputs.tag}}.md
        github_token: ${{ steps.github_app_token.outputs.token }}
name: Releases
on:
  repository_dispatch:
    types: trigger-ga___auto-release.yml
