jobs:
  backport:
    if: "github.event.pull_request.merged && (\n  github.event.action == 'closed'\n\
      \  || (\n    github.event.action == 'labeled'\n    && contains(github.event.label.name,\
      \ 'backport')\n  )\n)\n"
    name: Backport
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: github_app_token
      name: GitHub App token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.APP_ID }}
        installation_id: 22958780
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - continue-on-error: true
      name: Backport
      uses: VachaShah/backport@v2.2.0
      with:
        failure_labels: backport-failed
        github_token: ${{ steps.github_app_token.outputs.token }}
        head_template: backport/backport-<%= number %>-to-<%= base %>
name: Backport
on:
  repository_dispatch:
    types: trigger-ga___backport.yml
