jobs:
  verify-changelog:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      id: verify-changelog-3x
      uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: CHANGELOG-3.0.md
        skipLabels: autocut, skip-changelog
    - continue-on-error: true
      id: verify-changelog
      uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: CHANGELOG.md
        skipLabels: autocut, skip-changelog
    - continue-on-error: true
      run: "# The check was possibly skipped leading to success for both the jobs\n\
        if [[ ${{ steps.verify-changelog-3x.outcome }} == 'success' && ${{ steps.verify-changelog.outcome\
        \ }} == 'success' ]]; then\n  exit 0\nfi\n\nif [[ ${{ steps.verify-changelog-3x.outcome\
        \ }} == 'failure' && ${{ steps.verify-changelog.outcome }} == 'failure' ]];\
        \ then\n  echo \"error: Please ensure a changelog entry exists in CHANGELOG.md\
        \ or CHANGELOG-3.0.md\"\n  exit 1\nfi\n\n# Concatenates the labels and checks\
        \ if the string contains \"backport\"\nhas_backport_label=${{ contains(join(github.event.pull_request.labels.*.name,\
        \ ', '), 'backport')}}\nif [[ ${{ steps.verify-changelog.outcome }} == 'success'\
        \ && $has_backport_label == false ]]; then\n  echo \"error: Please make sure\
        \ that the PR has a backport label associated with it when making an entry\
        \ to the CHANGELOG.md file\"\n  exit 1\nfi\n"
name: Changelog Verifier
on:
  repository_dispatch:
    types: trigger-ga___changelog_verifier.yml
