jobs:
  copy-issue-labels:
    if: github.repository == 'opensearch-project/OpenSearch'
    permissions:
      contents: read
      issues: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: copy-issue-labels
      uses: michalvankodev/copy-issue-labels@v1.3.0
      with:
        labels-to-exclude: 'untriaged

          triaged

          '
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Copy labels from linked issues
on:
  repository_dispatch:
    types: trigger-ga___copy-linked-issue-labels.yml
