env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  create-issue:
    if: ${{ github.event.label.name == 'needs-documentation' }}
    name: Create Documentation Issue
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: github_app_token
      name: GitHub App token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.APP_ID }}
        installation_id: 22958780
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Edit the issue template
      run: 'echo "https://github.com/opensearch-project/OpenSearch/pull/${{ env.PR_NUMBER
        }}." >> ./ci/documentation/issue.md

        '
    - continue-on-error: true
      id: create-issue
      name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v5
      with:
        content-filepath: ./ci/documentation/issue.md
        labels: documentation
        repository: opensearch-project/documentation-website
        title: Add documentation related to new feature
        token: ${{ steps.github_app_token.outputs.token }}
    - continue-on-error: true
      name: Print Issue
      run: echo Created related documentation issue ${{ steps.create-issue.outputs.issue-number
        }}
name: Create Documentation Issue
on:
  repository_dispatch:
    types: trigger-ga___create-documentation-issue.yml
