jobs:
  build-and-publish-snapshots:
    if: github.repository == 'opensearch-project/OpenSearch'
    permissions:
      contents: write
      id-token: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.PUBLISH_SNAPSHOTS_ROLE }}
    - continue-on-error: true
      name: Publish snapshots to maven
      run: 'export SONATYPE_USERNAME=$(aws secretsmanager get-secret-value --secret-id
        maven-snapshots-username --query SecretString --output text)

        export SONATYPE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id
        maven-snapshots-password --query SecretString --output text)

        echo "::add-mask::$SONATYPE_USERNAME"

        echo "::add-mask::$SONATYPE_PASSWORD"

        ./gradlew publishNebulaPublicationToSnapshotsRepository

        '
name: Publish snapshots to maven
on:
  repository_dispatch:
    types: trigger-ga___publish-maven-snapshots.yml
