jobs:
  stale:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: github_app_token
      name: GitHub App token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.APP_ID }}
        installation_id: 22958780
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - continue-on-error: true
      name: Stale PRs
      uses: actions/stale@v9
      with:
        days-before-issue-close: -1
        days-before-issue-stale: -1
        days-before-pr-close: -1
        days-before-pr-stale: 30
        repo-token: ${{ steps.github_app_token.outputs.token }}
        stale-pr-label: stalled
        stale-pr-message: This PR is stalled because it has been open for 30 days
          with no activity.
name: Label Stalled PRs
on:
  repository_dispatch:
    types: trigger-ga___stalled.yml
permissions:
  pull-requests: write
