jobs:
  apply-label:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/github-script@v7.0.1
      with:
        script: "const { issue, repository } = context.payload;\nconst { number, body\
          \ } = issue;\nconst { owner, name } = repository;\nconst regex = /###\\\
          sRelated\\scomponent\\n\\n(\\w.*)\\n/gm;\nlet match;\nwhile ( ( match =\
          \ regex.exec( body ) ) ) {\n  const [ , component_label ] = match;\n  await\
          \ github.rest.issues.addLabels( {\n    owner: owner.login,\n    repo: name,\n\
          \    issue_number: number,\n    labels: [ `${ component_label }` ],\n  }\
          \ );\n}\ngithub.rest.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: ['untriaged']\n\
          })\n"
name: Auto triage based on the component label in issue
on:
  repository_dispatch:
    types: trigger-ga___triage.yml
